- hosts: all
  become: true
  pre_tasks:
    - name: pre-run | update package cache (ubuntu)
      tags: always
      apt: update_cache=yes
      changed_when: False

- hosts: all
  become: true
  tasks:
    - name: install apache
      tags: apache
      apt:
        - apache2
